### ISSUE TITLE
[CSi3] --release keybinds still show --release

### ISSUE THREAD

**Issue by The-Repo-Club** [terminalforlife/Extra#17]
when using --release i think it would be nicer if it had a green ! or ? at the start instead of showing the --release

**Comment by The-Repo-Club** [comment]
i also tried this line `Action=${Action/--release /!}` but it didn't do anything

**Comment by terminalforlife** [comment]
'ello. Is this about CSi3?

**Comment by The-Repo-Club** [comment]
> 'ello. Is this about CSi3?

yes sir sorry forgot to say what it was for my bad

**Comment by terminalforlife** [comment]
No worries. Thanks for renaming the title. :)

**Comment by The-Repo-Club** [comment]
ya anything could work just an idea :) just need to find something to show thats its a release without the --release text :)
