### ISSUE TITLE
lmc-darklight, check already active

### ISSUE THREAD

**Issue by vimes666** [terminalforlife/Extra#22]
Hi,
In your video you advised to define it in 'startup applications' and to do a login/logout when you change the script.
Be aware though that when you log out and in again (without reboot) there will be multiple instances running as the script will not be stopped on logout.
You might want to add some coding to prevent it from running multiple instances or move the startup from 'startup applications' to a user cronjob.

**Comment by terminalforlife** [comment]
That sounds like the first video, before it got overhauled. You don't need to log out then in with LMC-DarkLight anymore. I recommend [this](https://www.youtube.com/watch?v=qH271wrxpkE) video.

However, this is absolutely a problem I didn't know existed in Linux Mint. Perhaps I'm so used to `pkill -u USER` to log out. I made [this](https://forums.linuxmint.com/viewtopic.php?f=213&t=368883&p=2145213#p2145213) post, in hopes someone there knows why logging out isn't killing processes started with Startup Applications GUI.

This is definitely a problem and now my immediate concern. Thanks for letting me know.

**Comment by vimes666** [comment]
`Its` a nuisance for sure, I ran into it some years ago.
Normally I use someting like this:
```
for pid in $(pidof -x "${0##*/}"); do
   if [ $pid != $$ ]; then
      kill $pid"
   fi
done
```
Hope it helps.

**Comment by terminalforlife** [comment]
Yeah, I'm doing something like:

```bash
if [[ -f $Running ]]; then
	[[ -r $Running ]] || Err 1 "File '$Running' unreadable."

	read < "$Running"
	kill -HUP ${REPLY//[![:digit:]]} || exit 4
fi

printf '%d\n' $$ > "$Running"
```

The `$Running` variables is the path to flag file in which is stored the PID of the running instance. This isn't working properly, though. I'm probably being blonde, because I'm so mentally drained and can barely think. -_-

**Comment by terminalforlife** [comment]
It seemed to be working, but it actually isn't. This is frustrating.

**Comment by vimes666** [comment]
try this:
for PID in `pidof -x $Progrm`; {
	(( $PID == $$ )) || kill -HUP $PID
}
You forgot the dollar sign :)
Btw: you shouldnt user variables consisting of uppercase only. Those are 'sort of' reserved for environment variables.

**Comment by terminalforlife** [comment]
It wasn't the sigil, because it wasn't needed there, due to how arithmetic expansion/evaluation works in BASH.

Seems to be working now, with that last commit. If you get the chance, please confirm. It's working on my Linux Mint 20.3 Cinnamon virtual machine. I hope it's good now, because that was stressful trying to fix that ASAP. Lol

**Comment by vimes666** [comment]
I cannot confirm fully because I didnt install it. It would interfere with my own background script and I am on mate right now.
You are right about the dollar-sign, I was misled by differences in the trace output when I tested that piece of coding.
```
vimes@Terry:~$ lmc-darklight
+ Progrm=lmc-darklight
++ pidof -x lmc-darklight
+ for PID in `pidof -x $Progrm`
+ ((  PID == 83929  ))
vimes@Terry:~$ lmc-darklight
+ Progrm=lmc-darklight
++ pidof -x lmc-darklight
+ for PID in `pidof -x $Progrm`
+ ((  84653 == 84653  ))
```
Both tries gave the same correct logic result though (first one without, second with dollar)
I will try to install it on my test pc tonight.

**Comment by vimes666** [comment]
And an addition. I tried starting it again (to test what I was supposed to test) and got another error:
```
vimes@tiffany:~$ lmc-darklight 
/usr/bin/lmc-darklight: line 106: kill: (11493) - No such process
Err: Unable to kill old 11493 instance.
```
I suppose that has to do with the undocumented switch (at least in my man page) you are using in the kill command.

**Comment by vimes666** [comment]
I will do a clean test tomorrow, have to catch some sleep now. LMDE should behave the same as the normal cinnamon with respect to the themes so I guess it will all work as long as you adjust the test for a valid mint system to conform with the data from my /etc/os-release file I pasted earlier.

**Comment by terminalforlife** [comment]
Well, right now, LMC-DarkLight is "officially" for regular Linux Mint, but I'd love to have it work properly in LMDE. I'll have the distribution check accept LMDE if I can get it working properly in LMDE. For now, you'll need to use the `-f` flag to override that check.

Good night. :) And thanks very much for the testing.

**Comment by bobscotland** [comment]
The `lmc-darklight -f` works for starting the process on LMDE4, but after logging out and in again the theming wasn't working. Running it from the terminal resulted in the in your "Unable to kill old $PID instance error." It appears that its reading the old PID from the `$Current` file and trying to kill a non-existing PID.

I modified (read "sullied") your code to remove the `$Current` file if the PID it contains doesn't exist, but return your error if the PID exists but can't be killed. Seems to work OK, theming changes when logging in now. Not sure how safe this is though, I'm no programmer, and a total noob to Bash and GitHub.

```
if (( $(pgrep -c $PID) == 0 )); then
        rm "$Current"
else
    	kill -HUP $PID || Err 1 "Unable to kill old $PID instance."
fi
```

**Comment by terminalforlife** [comment]
Thanks, Bob. I'm so confused as to why it's working in regular Mint and not LMDE. You're definitely on the latest version of LMC-DarkLight and deleted any existing `$Current` file? I think the reason it's failing for you guys is because you have that leftover PID file from the previous version.

I'm trying to set up LMDE 4 in a virtual machine, but it seems like such a buggy distribution. IDK how you guys are you using it. It's freshly-installed and I can't even update the package cache or do anything with packages, and changing mirrors doesn't seem to be doing anything.

I guess, as an alternative, you could try running LMC-DarkLight from '~/.profile' instead, because when you log out, that script should end, thus LMC-DarkLight should end. Unfortunately, that's an imperfect solution, too. This is _**incredibly**_ frustrating.

**Comment by terminalforlife** [comment]
That seems to have corrected it. It's working in both my LMDE 4 and Linux Mint virtual machines.

**Comment by bobscotland** [comment]
Hi, regarding your issue with updating the LMDE repos (although you've probably found the solution by now) use this command `sudo apt update –allow-releaseinfo-change` and it should update OK after that. Things still working OK this end with the latest release of lmc-darklight.

**Comment by terminalforlife** [comment]
Awesome. Since things are finally working, I guess it's time to close this Issue. Guys, I can't say enough how grateful I am for the assist. :)
