### ISSUE TITLE
Convert AutoExec to fswatch based tool

### ISSUE THREAD

**Issue by reportaman** [terminalforlife/Extra#24]
fswatch is a cross platform file system monitor. One could detect change in a file or a set of files and run a command. Given it uses the OS utilities meant for this purpose, it won't consume CPU time while waiting for files to change.

https://github.com/emcrisostomo/fswatch
https://medium.com/@chapuyj/automatically-run-tests-when-a-change-occurs-9bae2140586b

**Comment by terminalforlife** [comment]
I appreciate the suggestion. However, I don't think it's suitable for AE, as it doesn't seem to align with AE as a general development tool. It would also add unneeded complexity.

That being said, I _could_ write a _separate_ tool similar to AE, but for simply running a command when a file's contents has been touched; it would sort of be like AE's little brother, for more general and simple use. What do you think? What would be the use-case for such a tool?
