### ISSUE TITLE
ubuntu-syschk: 'Too few arguments'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [terminalforlife/Extra#3]
Hello!

`$ ./ubuntu-syschk`

produces

`Too few arguments`

but proceeds anyway. I suspect the error owes to the script's line

`systemd-analyze verify`

which, when run separately, produces the same error message. I think I lack the version of systemd that is needed for that command.

**My system**

OS: Linux Mint 19.3 Tricia x86_64 
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th 
Kernel: 5.3.18-050318-generic 
Uptime: 23 mins 
Packages: 3329 (dpkg), 13 (flatpak), 7 (snap) 
Shell: bash 4.4.20 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 4.4.8 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark (N_Cinn) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
Memory: 2692MiB / 15907MiB 
Disk (/dev/nvme0n1p4): 19G / 40G (51%) 
Disk (/dev/nvme0n1p2): 166G / 405G (44%) 
Disk (udev): 0 / 7.8G (0%) 

PS: Also, the script generates much along the lines of

`ALERT: Low remaining storage space detected: /dev/loop0`

which I feel perhaps it should not.

**Comment by terminalforlife** [comment]
I really appreciate the bug report! I'll work on that today.

**Comment by LinuxOnTheDesktop** [comment]
Thanks.

I don't think that in my case the script recommended anything kernel parameter-wise. Or if it did then I did not realise that that was what it was suggesting! Relatedly, perhaps: it seemed that various things the script recommended were settable in `/etc/sysctl.conf`'; perhaps those are settable as kernel parameters. Actually, though, I had set some of those values in that file - set them to the values the script wanted - and the script seemed not to notice. Or rather it complained about what it called the 'defaults' for those values, i.e. it ignored the fact that I had set those values in that file.

**Comment by terminalforlife** [comment]
Did you restart after setting them? AFAIK, they don't take effect until you reboot, unless you enable them directly, using:

```
sudo sysctl vm.swappiness=3
```

or

```
sudo sh -c 'echo 3 > /proc/sys/vm/swappiness'
```

The latter method of which is not permanent.

**Comment by LinuxOnTheDesktop** [comment]
By the way: I find that implementing what the program suggested for the mount options of /tmpfs broke things. Specifically, it broke third-party launchers. More specifically: I have two programs, namely ulauncher and gmrun; what those programs do, is run (other) programs; yet, after setting the `noexec` mount option for tmps (as your script recommended), those two programs no longer worked with anything requiring `pkexec`, i.e. they could not launch 'elevated' stuff. I suppose this might be a case of 'working as intended' but that is a consequence people do not expect.

**Comment by terminalforlife** [comment]
Yeah, you're quite right, and I've ran into similar problems in the past, like with Steam. That's where it's up to the user how he or she wants to handle what the script tells them. It's a system tool, after all. I plan to make UbuChk (the Perl rewrite and overhaul) descriptive of the suggestions, in a similar capacity to ShellCheck.

**Comment by LinuxOnTheDesktop** [comment]
That all sounds good. Unfortunately for the next few months I may not have time for any testing.

**Comment by terminalforlife** [comment]
Oh, that's a shame. Well, I hope to see you around the Git of Hubs when you get back. :)

**Comment by LinuxOnTheDesktop** [comment]
Better than the Hub of Gits! (It's a shame also that it's owned by Microsoft, though there's some reason to think Microsoft is less pernicious than previously.)

**Comment by terminalforlife** [comment]
Lol Agreed, on both accounts. I thought about moving to GitLab, and maybe I will one day, but I've already put up shop over here and have been here for years, so I kinda feel stuck.

**Comment by terminalforlife** [comment]
Closing this issue now, since it's not been relevant for a while, because of it being deprecated by UbuChk.
