### ISSUE TITLE
AutoExec: Support for JavaScript

### ISSUE THREAD

**Issue by dev-casual** [terminalforlife/Extra#4]
Fantastic idea, love the execution. Anyway possible to bring in Javascript? I have been looking for something like this for a while now. A big IDE surely can fullfil my needs, but it ain't the same. Thanks in advance.

**Comment by terminalforlife** [comment]
Thank you. :) However, you've not said to _which_ project you're referring. :P I'm guessing AutoExec.

**Comment by dev-casual** [comment]
I'm sorry, yes, you are right, I meant autoexec. I thought autoexec had its own repository. Gotta live up to my name I guess. 

I'm aware that this has the dependency to NodeJS, deno or some other JS runtime. Right now I'm just sending a file into a loop, but it is absolutely not efficent.

**Comment by terminalforlife** [comment]
LOL That was funny, because I didn't notice your name before, but it just clicked for comical effect. :D

I'll look into the possibility of adding NodeJS support, but no promises. _If_ I went for it, would you be willing to help with testing? I could set up a separate, temporary branch for this feature.

**Comment by dev-casual** [comment]
Sure, I will gladly test it! Right now I'm just searching for an easy way to console.log() sanely with two terminal windows to debug and test some multiliners. Hardcore coding isn't my strength, I'm more of a scripter, so I cannot go very deep on this.

My (limited) experience with Github repositories isn't of much help here. But can I just state that this conversation is so much more friendly than many of those I have read in other projects. Thanks for that!

**Comment by dev-casual** [comment]
Yes, you are absolutely right, `autoexec -e node foo.js` does work, holy hell. Stop all thinking and developing. Comes to show, that I should have read the man page a little bit better instead of just `autoexec foo.js`

It does work, and it does work well for my workflow :)

**Comment by terminalforlife** [comment]
Lol Woo, that saves me hassle. :P I'll still look into a way for Node.js files to be detected by default, but if it's not reliable enough, I'll have to abandon that idea. Been a while since I've messed with Node.js; any ideas how you could reliably identify it as such a file?

**Comment by dev-casual** [comment]
I would have no problem with the standard shebang + env to be honest. 

Only thing bugging me, but that is _really_ nitpicky and not worth any hassle, is that I sometimes scroll in autoexec which leads to terminal breakage with the characters.

**Comment by terminalforlife** [comment]
Do you mean scrolling with the mouse wheel?

OH! I forgot there's a way to turn off 'echo' (not the builtin), which basically stops any input displaying on the terminal. If it's possible to do that but also maintain control of AE, so the user can ^C it, then would be golden. I'll look into that in a bit.

**Comment by dev-casual** [comment]
I just tested it without `#!/usr/bin/env node` and it worked just fine. Sorry, QA isn't my strenght. I'm just happy when something is working :)
